excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - fastlane
disabled_rules: # rule identifiers to exclude from running
  - closure_parameter_position
  - force_cast
  - force_try
  - notification_center_detachment
  - identifier_name
  - line_length
  - function_body_length
  - file_length
  - closure_end_indentation
  - cyclomatic_complexity
  - nesting
  - valid_ibinspectable
opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - object_literal
  - pattern_matching_keywords
  - private_action # ?
  - private_outlet # ?
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - valid_ibinspectable
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
trailing_whitespace:
  ignores_empty_lines: true
inclusive_language:
  override_allowed_terms: ["master"]
