name: 🐞 Issue report
description: Report a issue in NineAnimator
labels: [bug]
body:

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: nineanimator-version
    attributes:
      label: NineAnimator version
      description: |
        You can find your NineAnimator version in **Settings**.
      placeholder: |
        Example: "1.2.7"
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS version
      description: |
        You can find this somewhere in your Android settings.
      placeholder: |
        Example: "iOS 13"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
