#
#  This file is part of the NineAnimator project.
#
#  Copyright © 2018-2020 Marcus Zhou. All rights reserved.
#
#  NineAnimator is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  NineAnimator is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with NineAnimator.  If not, see <http:#www.gnu.org/licenses/>.
#

default_platform :ios

platform :ios do
    
    ### Screenshot Automation Lane
    desc "Generate new localized screenshots"
    lane :screenshots do
        capture_screenshots(
            output_directory: "fastlane/screenshots",
            scheme: "ScreenshotAutomation"
        )
        frame_screenshots(path: "./fastlane/screenshots")
    end
    
    desc "Remove inactive users on TestFlight"
    lane :clean_testers do
        clean_testflight_testers(
            days_of_inactivity: 120
        )
    end
    
end
