# A list of devices you want to take the screenshots from
devices([
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone 8 Plus",
  "iPhone 8",
  "iPad Pro (9.7-inch)",
  "iPad Pro (11-inch)",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
  "en-US"
])

scheme "ScreenshotAutomation"
project "./NineAnimator.xcodeproj"
clear_previous_screenshots true
dark_mode true
derived_data_path "./fastlane/derived_data"
